WHITESPACE = _{ " " | "\t" | NEWLINE }
COMMENT = _{ ("//" ~ (!NEWLINE ~ ANY)* ~ NEWLINE) | "/*" ~ (!"/" ~ ANY) ~ "*/" }

// Keywords
keyword = { "use" | "if" | "while" | "else" | "return" | "length" | "true" | "false" | "int" | "char" | "bool" }

// Identifiers
identifier = @{ (!keyword) ~ ASCII_ALPHA ~ (ASCII_ALPHA | ASCII_DIGIT | "_" | "'")* }

// Literals
int_lit = @{ "-"? ~ ASCII_NONZERO_DIGIT ~ ASCII_DIGIT* ~ !ASCII_ALPHA | "0" }
bool_lit = @{ "true" | "false" }
string_lit = @{ "\"" ~ (raw_str | esc_str)* ~ "\"" }
raw_str = _{ (!("\\" | "\"" | "\n") ~ ANY)+ }

esc_str = _{"\\" ~ (predef_esc | unicode)}

predef_esc = _{ "\\" | "n" | "t" | "\"" | "'"}
unicode = _{ "x{" ~ 
  (
    "0" ~ ASCII_HEX_DIGIT{5}
    | "10" ~ ASCII_HEX_DIGIT{4} 
    | ASCII_HEX_DIGIT{1,5} 
  ) 
~ "}" }

char_lit = { "'" ~ ( !("\\" | "'") ~ ANY | esc_str ) ~ "'" }

literal = { string_lit | char_lit | int_lit | bool_lit | identifier}

// Symbols
left_brack = { "[" }
right_brack = { "]" }
left_curly = { "{" }
right_curly = { "}" }
left_paren = { "(" }
right_paren = { ")" }
colon = { ":" }
comma = { "," }
semi = { ";" }
underscore = { "_" }

// Binary Operators 
plus = { "+" }
minus = { "-" }
high_multiply = { "*>>" }
times = { "*" }
divide = { "/" }
modulo = { "%" }
and = { "&" }
or = { "|" }
geq = { ">=" }
gt = { ">" }
leq = { "<=" }
lt = { "<" }
eq = { "==" }
neq = { "!=" }
assign = { "=" }
binary_op = {
  | plus 
  | minus 
  | high_multiply 
  | times 
  | divide
  | modulo 
  | and 
  | or 
  | geq 
  | gt 
  | leq 
  | lt 
  | eq 
  | neq 
  | assign 
}

// Unary Operators
not = { "!" }
neg = { "-" }
unary_op = { not | neg }

// Function Call 
argument = { expr } // You can expand this to include other types of expressions
arguments = { argument ~ ("," ~ argument)* }
function_call = { identifier ~ "(" ~ (arguments)? ~ ")" }

// Array Literals 
expr_list = { ((expr ~ ("," ~ expr)* ~ ","?))? }
array_lit = { "{" ~ expr_list ~ "}" }

// Array Indexing 
index = { expr }
array_index = { identifier ~ "[" ~ index ~ "]" }

// Expressions 
len_expr = { "len" ~ "(" ~ expr ~ ")" } 

primary = {
  | array_index
  | len_expr 
  | function_call 
  | literal 
  | identifier
  | array_lit
}

binary_expr = { primary ~ binary_op ~ expr }
unary_expr = { unary_op ~ expr }
expr = {
  | binary_expr 
  | unary_expr 
  | primary
}

// Types 
int_type = { "int" }
bool_type = { "bool" }
char_type = { "char" }
void_type = { "void" }
empty_bracket = { "[]" }
sized_bracket = { "[" ~ expr ~ "]" }
primitive_type = { int_type | bool_type | char_type }
array_sized_type = { primitive_type ~ (sized_bracket+ ~ empty_bracket*) }
array_unsized_type = { primitive_type ~ empty_bracket+ }
array_type = { array_sized_type | array_unsized_type }
decl_type = { array_type | primitive_type }

// Statements 
block = { "{" ~ (statement)* ~ "}" }
if_stmt = { "if" ~ (("(" ~ expr ~ ")") | expr) ~ block ~ ("else" ~ block)? }
while_stmt = { "while" ~ (("(" ~ expr ~ ")") | expr) ~ block }
return_stmt = { "return" ~ expr_list ~ semi }
identifier_list = { identifier ~ ("," ~ identifier)*? }
assign_stmt = { identifier_list ~ "=" ~ expr_list ~ semi }
decl_stmt = { decl_type ~ identifier_list ~ "=" ~ expr_list ~ semi }
procedure_call = { function_call ~ semi }
statement = { if_stmt | while_stmt | return_stmt | assign_stmt | decl_stmt | procedure_call | block }

// Function Declarations 
type_list = { decl_type ~ ("," ~ decl_type)*? }
return_type = { void_type | type_list }
args = { ((decl_type ~ identifier) ~ (("," ~ (decl_type ~ identifier)))*)? }
function_decl = { return_type ~ identifier ~ left_paren ~ args ~ right_paren ~ block }

// Global Declarations 
global_decl = { decl_stmt }

// Use Statements 
use_stmt = { "use" ~ identifier ~ semi }

// Program 
program = { (use_stmt)* ~ (global_decl)* ~ (function_decl)* }